services:
  web:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
